### ISSUE TITLE
The result from OPT is not correct 

### ISSUE THREAD

**Issue by 1a1a11a** [trauzti/cache#2]
a sample data: 
4
1
2
2
1
4
1
0
4
4
with cache size=1, then we should get hit count of 3, but current version of OPT gives 2.

**Comment by trauzti** [comment]
2
2

and

4
4

will be hits but what should be the third hit?

**Comment by 1a1a11a** [comment]
1
1 
from 1, 4, 1 (4 won't be cached)

**Comment by 1a1a11a** [comment]
@trauzti see above

**Comment by trauzti** [comment]
Why won´t 4 be cached? OPT is seeing a new entry and will evict the one
that will be used again furthest in the future. Since it only keeps info on
one entry at a time with cache size=1 it has to evict 1.

**Comment by 1a1a11a** [comment]
@trauzti yes, it keeps the entry that will be used the earliest in the future, so 4 won't be cached, as in seq `1, 4, 1`, the first 1 will be used earlier in the future than 4, so why cache 4 instead of 1? Am I miss something?

**Comment by trauzti** [comment]
Okay see your point, to do that you are basically skipping an eviction when
the already cached entry should stay in the cache.

**Comment by 1a1a11a** [comment]
I see your point, so in your version, there must be at least one eviction when inserting (and cache is full), right? In other words, we just have two different versions of OPT. I bring this up because we have  some strange observation of OPT in other data and trying to confirm my version of OPT is correct.

**Comment by trauzti** [comment]
Closing issue because I want this implementation to always cache the referenced element.
